### ISSUE TITLE
trying to run this on core 2.4

### ISSUE THREAD

**Issue by Rtully** [ajvdw/HexAJpod#1]
Hi i'm trying to run this first on latest core with no luck and then with core 2.4-rc1 and 2.3 it compiles OK, the web control app opens ok but no movement on servos, have tried pins D1 D2 and pins D5 D6 and other combinations with no luck, any ideas please?

**Comment by ajvdw** [comment]
Please note that it runs on an ESP8266. The ESP uses I2c to control 2 12-bit PWM/Servo Driver-I2C interface Module each controlling 16 channels

**Comment by Rtully** [comment]
Yes I know, that is what i have setup. the i2c doesn't seem to be communicating with the PCA9685 s, I can see the servo messages in the serial monitor when i connect to the webapp but the message doesn't seem to be reaching the servo drivers.

**Comment by ajvdw** [comment]
Does your i2c communication work? Proper addresses?

**Comment by Rtully** [comment]
If i run a test sketch with the current adafruit driver on ESP core 2.4.2 the i2c works ok, (but thats with a "wire.begin (4, 5)").
Then your code won't compile on 2.4.2 so I got it to compile using 2.3 core, the webapp etc works fine but no movement on servos at all (i think its the i2c) I have tried using several pin combinations but the defaults should be GPIO4 and GPIO5 by default no? On this i can see the loop running on IDE serial monitor when app connects. I can not find in the code any other references to pins for i2c so presume they will be the defaults.

Finally, out of despiration, I have tried to port the code to work with the current Adafruit PWM driver and ESP core 2.4.2, by changing the define servo driver in phoenix.cpp to 

"// Define our ServoDriver objects
Adafruit_PWMServoDriver g_ServoDriverR = Adafruit_PWMServoDriver(0x41);  
Adafruit_PWMServoDriver g_ServoDriverL = Adafruit_PWMServoDriver(0x40);"

I changed the "include library" in to the "#include <Adafruit_PWMServoDriver.h>" instead of "include "servodriver.h""
I also had to change the server line in Hexapod8266.ino
"// Web Server
ESP8266WebServer server (80);"
It all connects the same as the original code on core 2.3. The webapp connects fine on my phone and as soon as it connects in the serial monitor on the IDE I can see the loop of servo commands running. This is what leads me to think it's an i2c pin problem? I'm using a nodeMCU V1.0 12E and two PCAS9685's. Thanks so much for any help, I've been two days trying to get this running.

**Comment by Rtully** [comment]
what i'm getting on serial monitor with debug core.
Setting PWM 0: 0->369
Setting PWM 1: 0->210
Setting PWM 2: 0->259
Setting PWM 15: 0->375
Setting PWM 14: 0->540
Setting PWM 13: 0->491
Setting PWM 4: 0->375
Setting PWM 5: 0->210
Setting PWM 6: 0->259
Setting PWM 11: 0->375
Setting PWM 10: 0->540
Setting PWM 9: 0->491
Setting PWM 8: 0->368
Setting PWM 9: 0->208
Setting PWM 10: 0->255
Setting PWM 7: 0->375
etc etc...

**Comment by ajvdw** [comment]
I agree, it must be the i2c code.
You should first try some sample  (for the Adafruit driver) code to get 1 servo to move.
Than work out the differences with my code. It comes down to 3 or 4 lines of code.

https://learn.adafruit.com/16-channel-pwm-servo-driver/hooking-it-up
I remember adjusting the Adafruit driver code because the original didn't work in my case.

**Comment by Rtully** [comment]
i have gone through the adafruit code and it all seems pretty similar, apart from the lines that didnt work originally for you which have changed a bit since. i have also tried with your servo driver code, i have the pwm drivers attached to GPIO 4 and 5 and with a i2c checker sketch they show up fine and with correct addresses. I have also had servos moving fine using adafruit test sketches with adafruit drivers....

**Comment by Rtully** [comment]
handleFileRead: /remote.css
handleFileRead: /ocanvas-2.8.3.min.js
[0] Connected from 192.168.4.2 url: /
Setting PWM 0: 0->375
Setting PWM 1: 0->210
Setting PWM 2: 0->259
Setting PWM 15: 0->375
Setting PWM 14: 0->540
Setting PWM 13: 0->491
Setting PWM 4: 0->375
Setting PWM 5: 0->210
Setting PWM 6: 0->259
Setting PWM 11: 0->375
Setting PWM 10: 0->540
Setting PWM 9: 0->491
Setting PWM 8: 0->375

**Comment by Rtully** [comment]
Hexapod v0.2
Setup SPIFFS
FS File: /favicon.ico, size: 1.12KB
FS File: /apple-touch-icon-120x120.png, size: 1.82KB
FS File: /remote.css, size: 609B
FS File: /ocanvas-2.8.3.min.js, size: 71.68KB
FS File: /rotateplease.png, size: 1.75KB

Setup Wifi
Init Controller
Config loaded
Start Websocket
Start mDNS
Start Webserver
Setup i2c
Init Phoenix
Running loop ...
handleFileRead: /remote.css
handleFileRead: /ocanvas-2.8.3.min.js
[0] Connected from 192.168.4.2 url: /

**Comment by Rtully** [comment]
the previous is the original code runing on core 2.3. This is the modified code (adafruit driver) runing on lates 2.5.0 beta2:


Hexapod v0.2
Setup SPIFFS

Setup Wifi
Init Controller
Config loaded
Start Websocket
Start mDNS
Start Webserver
Setup i2c
Init Phoenix
Attempting to set freq 1000.00
Estimated pre-scale: 5.78
Final pre-scale: 6
Mode now 0xFF
Attempting to set freq 60.00
Estimated pre-scale: 112.03
Final pre-scale: 112
Mode now 0xFF
Attempting to set freq 1000.00
Estimated pre-scale: 5.78
Final pre-scale: 6
Mode now 0xFF
Attempting to set freq 60.00
Estimated pre-scale: 112.03
Final pre-scale: 112
Mode now 0xFF
Setting PWM 0: 0->375
Setting PWM 1: 0->375
Setting PWM 2: 0->375
Setting PWM 15: 0->375
Setting PWM 14: 0->375
Setting PWM 13: 0->375
Setting PWM 4: 0->375
Setting PWM 5: 0->375
Setting PWM 6: 0->375
Setting PWM 11: 0->375
Setting PWM 10: 0->375
Setting PWM 9: 0->375
Setting PWM 8: 0->375
Setting PWM 9: 0->375
Setting PWM 10: 0->375
Setting PWM 7: 0->375
Setting PWM 6: 0->375
Setting PWM 5: 0->375
Running loop ...

**Comment by Rtully** [comment]
ok sorry 2.5 beta2 didnt work. in 2.4.2 it is connecting and recieveing from the webapp but still no joy with the servos themselves:

:rch 46, 13
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[readCb] n: zu t: 2
:rch 59, 10
:rd 2, 59, 0
:rdi 12, 2
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 1 payloadLen: 6
[WS][0][handleWebsocketWaitFor] size: 6 cWsRXsize: 2
[readCb] n: zu t: 4
:rd 4, 69, 2
:rdi 10, 4
[WS][0][handleWebsocketWaitFor][readCb] size: 6 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 1 payloadLen: 6
[readCb] n: zu t: 6
:rd 6, 69, 6
:rdi 6, 6
:c 6, 12, 69
[WS][0][handleWebsocket] text: #x,-50
:rch 57, 12
:rch 69, 12
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[readCb] n: zu t: 2
:rd 2, 81, 0
:rdi 11, 2
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 1 payloadLen: 5
[WS][0][handleWebsocketWaitFor] size: 6 cWsRXsize: 2
[readCb] n: zu t: 4
:rd 4, 81, 2
:rdi 9, 4
[WS][0][handleWebsocketWaitFor][readCb] size: 6 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 1 payloadLen: 5
[readCb] n: zu t: 5
:rd 5, 81, 6
:rdi 5, 5
:c 5, 11, 81
[WS][0][handleWebsocket] text: #y,69
:rch 70, 12
:rch 82, 12
[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[readCb] n: zu t: 2
:rd 2, 94, 0
:rdi 12, 2
[WS][0][handleWebsocketWaitFor][readCb] size: 2 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 1 payloadLen: 6
[WS][0][handleWebsocketWaitFor] size: 6 cWsRXsize: 2
[readCb] n: zu t: 4
:rd 4, 94, 2
:rdi 10, 4
[WS][0][handleWebsocketWaitFor][readCb] size: 6 ok: 1
[WS][0][handleWebsocket] ------- read massage frame -------
[WS][0][handleWebsocket] fin: 1 rsv1: 0 rsv2: 0 rsv3 0  opCode: 1
[WS][0][handleWebsocket] mask: 1 payloadLen: 6
[readCb] n: zu t: 6
:rd 6, 94, 6
:rdi 6, 6
:c 6, 12, 94
[WS][0][handleWebsocket] text: #x,-94
:rch 82, 11
:rch 93, 12
Setting PWM 0: 0->377
Setting PWM 1: 0->228
Setting PWM 2: 0->286
Setting PWM 15: 0->375
Setting PWM 14: 0->600
Setting PWM 13: 0->600
Setting PWM 4: 0->339
Setting PWM 5: 0->150
Setting PWM 6: 0->150
Setting PWM 11: 0->359
Setting PWM 10: 0->549
Setting PWM 9: 0->504
Setting PWM 8: 0->389
Setting PWM 9: 0->195
Setting PWM 10: 0->239
Setting PWM 7: 0->388
Setting PWM 6: 0->522
Setting PWM 5: 0->464

**Comment by Rtully** [comment]
this is the serial on boot in 2.4.2:
SDK:2.2.1(cfd48f3)/Core:2.4.2/lwIP:2.0.3(STABLE-2_0_3_RELEASE/glue:arduino-2.4.1-13-g163bb82)/BearSSL:6d1cefc



Hexapod v0.2
Setup SPIFFS
SPIFFSImpl: allocating 512+240+1400=2152 bytes
SPIFFSImpl: mounting fs @300000, size=fb000, block=2000, page=100
SPIFFSImpl: mount rc=0
FS File: /favicon.ico, size: 1.12KB
FS File: /apple-touch-icon-120x120.png, size: 1.82KB
FS File: /remote.css, size: 609B
FS File: /ocanvas-2.8.3.min.js, size: 71.68KB
FS File: /rotateplease.png, size: 1.75KB

Setup Wifi
Init Controller
Config loaded
Start Websocket
[WS-Server] Server Started.
Start mDNS
Start Webserver
Setup i2c
Init Phoenix
Attempting to set freq 1000.00
Estimated pre-scale: 5.78
Final pre-scale: 6
Mode now 0xFF
Attempting to set freq 60.00
Estimated pre-scale: 112.03
Final pre-scale: 112
Mode now 0xFF
Attempting to set freq 1000.00
Estimated pre-scale: 5.78
Final pre-scale: 6
Mode now 0xFF
Attempting to set freq 60.00
Estimated pre-scale: 112.03
Final pre-scale: 112
Mode now 0xFF
Setting PWM 0: 0->375
Setting PWM 1: 0->375
Setting PWM 2: 0->375
Setting PWM 15: 0->375
Setting PWM 14: 0->375
Setting PWM 13: 0->375

**Comment by ajvdw** [comment]
The changes I made are in this function, it's more efficient if you look at the number of commands send over the i2c lines.
You can revert back to the code you used when the servo was moving .....

void Servodriver::setPWM(uint8_t num, uint16_t on, uint16_t off) {
  //Serial.print("Setting PWM "); Serial.print(num); Serial.print(": "); Serial.print(on); Serial.print("->"); Serial.println(off);

  //This code didn't seem to work with chained i2c servo boards
  //Wire.beginTransmission(_i2caddr); 
  //Wire.write(LED0_ON_L+4*num);
  //Wire.write(on);
  //Wire.write(on>>8);
  //Wire.write(off);
  //Wire.write(off>>8);
  //Wire.endTransmission();

  write8((byte)(LED0_ON_L + 4 * num), (byte)on);
  write8((byte)(LED0_ON_H + 4 * num), (byte)(on >> 8));
  write8((byte)(LED0_OFF_L + 4 * num), (byte)off);
  write8((byte)(LED0_OFF_H + 4 * num), (byte)(off >> 8));
}

**Comment by Rtully** [comment]
Ok, I finally got it working with ESP core 2.4.2. The adafruit driver just doesn't work, i can get some servo noises when it connects but it has issues with the phoenix code as you said. I modified slightly your servo code to update some things that have changed in ESP Core 2.4.2 and Arduino since you wrote the original file:

the server line in Hexapod8266.h to:
// Web Server
ESP8266WebServer server (80);

and in the Servodriver.h changing:
"val = min(val, (4095);"
to
"val = min(val, (uint16_t)4095);"
I think that is all that changed in the end....
Onwards and upwards! Thanks so much for the help, now I plan to try to create a "controller" with a second esp8266 as slave and a gyro board.... Hopefully i can just send the same codes as the webapp javascript.

**Comment by Rtully** [comment]
Sorry could you tell me where on each PCA board goes each leg? Thanks

**Comment by ajvdw** [comment]
Board 1
0 RightRear Coxa
1 RightRear Femur
2 RightRear Tibia
4 RightMiddle Coxa
5 RightMiddle Femur
6 RightMiddle Tibia
8 RightFront Coxa
9 RightFront Femur
10 RightFront Tibia

Board 2
0 LeftRear Coxa
1 LeftRear Femur
2 LeftRear Tibia
4 LeftMiddle Coxa
5 LeftMiddle Femur
6 LeftMiddle Tibia
8 LeftFront Coxa
9 LeftFront Femur
10 LeftFront Tibia



Have a look at the function StartUpdateServos()
In that function all servo's are set one by one.

**Comment by Rtully** [comment]
thanks for all the help. Happy Christmas.
